In [2]:
import numpy as np

In [3]:
mat1D = np.array([1,2,3,4,5,6,7,8,9])
print(f"Array mat1D : {mat1D}")
print(f"Array mat1D + 10 :{mat1D + 10}")
print(f"Array mat1D indeks ke 2 :{mat1D[2]}")

Array mat1D : [1 2 3 4 5 6 7 8 9]
Array mat1D + 10 :[11 12 13 14 15 16 17 18 19]
Array mat1D indeks ke 2 :3


In [5]:
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Array mat2D : {mat2D}")
print(f"Array mat2D * 10:{mat2D * 10}")
print(f"Array mat2D indeks ke 2:{mat2D[2]}")
print(f"Array mat2D indeks ke 2:{mat2D[1][1] * 10}")

Array mat2D : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array mat2D * 10:[[10 20 30]
 [40 50 60]
 [70 80 90]]
Array mat2D indeks ke 2:[7 8 9]
Array mat2D indeks ke 2:50


In [6]:
print(mat1D.shape) #Mengetahui bentuk matriks
print(mat2D.shape)

(9,)
(3, 3)


In [7]:
print(mat1D.size) #Mengetahui ukuran dari matrtiks
print(mat2D.size)

9
9


In [18]:
#Special matriks
mZero = np.zeros((3,5)) #matriks dengan nilai 0
mOne = np.ones((4,4)) #matriks dengan nilai 1
mIdentity = np.eye((5)) #matriks diagonal 1 lainnya 0
mFull = np.full((3,3),7) #matriks dengan nilai yang sama
mF1Random = np.random.rand(5) #matriks dengan nilai acak float 5 kolom
mF2Random = np.random.rand(5,5) #matriks dengan nilai acak float 5 kolom
mI1Random = np.random.randint(10,100,size=10)
mI2Random = np.random.randint(1,100,size=(4,4))

print(f"Matriks mZero :\n {mZero}")
print(f"Matriks mOne :\n {mOne}")
print(f"Matriks mIdentity :\n {mIdentity}")
print(f"Matriks mFull :\n {mFull}")
print(f"Matriks mF1Random :\n {mF1Random}")
print(f"Matriks mF2Random :\n {mF2Random}")
print(f"Matriks mI1Random :\n {mI1Random}")
print(f"Matriks mI2Random :\n {mI2Random}")

Matriks mZero :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matriks mOne :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matriks mIdentity :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Matriks mFull :
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Matriks mF1Random :
 [0.04199352 0.66474978 0.61411241 0.39434069 0.02436776]
Matriks mF2Random :
 [[0.39588094 0.1992718  0.7012827  0.54871893 0.70116779]
 [0.40481035 0.83230891 0.77283486 0.50927345 0.32983828]
 [0.45781246 0.97973081 0.80056594 0.16591127 0.82866362]
 [0.45503567 0.40735186 0.47553383 0.93467465 0.75969383]
 [0.68255002 0.55065015 0.62208171 0.45521986 0.54572493]]
Matriks mI1Random :
 [21 67 99 35 43 76 33 13 59 61]
Matriks mI2Random :
 [[16 20 35 43]
 [53 15 64 26]
 [38 24 29 58]
 [39 67 87 12]]


In [22]:
#Aritmatic Array
x = np.array([1,2,3])
y = np.array([4,5,6])
r1 = np.dot (x,y) #perkalian dot product -> hasilnya adalah nilai skalar
r2 = np.add (x,y) #penjumlahan matriks dimana ordonya harus sama
r3 = np.dot (x,3) 

print(F"Hasil perkalian dot product : {r1}")
print(F"Hasil penjumlahan matriks :\n {r2}")
print(F"Hasil dot product dengan 3 :\n {r3}")

Hasil perkalian dot product : 32
Hasil penjumlahan matriks :
 [5 7 9]
Hasil dot product dengan 3 :
 [3 6 9]


In [27]:
#Fungsi statistik dasar
nilaiPemrograman = np.array ([100,90,80,80,50,50,50,40])
nilaiMin = np.min(nilaiPemrograman)
nilaiMax = np.max(nilaiPemrograman)
nilaiMean = np.mean(nilaiPemrograman)
nilaiSum = np.sum(nilaiPemrograman)
nilaiMedian = np.median(nilaiPemrograman)
nilaiStd = np.std(nilaiPemrograman)

print(f"Nilai Pemrograman :\n {nilaiPemrograman}")
print(f"Nilai Terkecil :{nilaiMin}")
print(f"Nilai Terbesar :{nilaiMax}")
print(f"Nilai Rata-rata :{nilaiMean}")
print(f"Total Nilai :{nilaiSum}")
print(f"Nilai Tengah :{nilaiMedian}")
print(f"Nilai Deviasi :{nilaiStd}")

#Filtering
#Mencari jumlah mahasiswa yang lulus -> nilai > 50
dataLulus = nilaiPemrograman[nilaiPemrograman > 50]
print(dataLulus)
print(f"Jumlah siswa yang lulus :{dataLulus.size}")

Nilai Pemrograman :
 [100  90  80  80  50  50  50  40]
Nilai Terkecil :40
Nilai Terbesar :100
Nilai Rata-rata :67.5
Total Nilai :540
Nilai Tengah :65.0
Nilai Deviasi :21.065374432940896
[100  90  80  80]
Jumlah siswa yang lulus :4
